### ISSUE TITLE
Update Dockerfile to use Rasterio 1.0

### ISSUE THREAD

**Issue by sarasafavi** [planetlabs/notebooks#58]
related reading: https://rasterio.readthedocs.io/en/latest/topics/migrating-to-v1.html

**Comment by jreiberkyle** [comment]
@sarasafavi We are using v1, alpha version ([see here](https://github.com/planetlabs/notebooks/blob/master/planet-notebook-docker/requirements.txt#L11)). So I think we are already migrated to v1. Should we look at a version update?

**Comment by sarasafavi** [comment]
Turns out there's a number of new features that 1.0.0 Final has vs our a12 pin, thanks to @geowurster for pointing this out. However there may be breaking changes in there to our existing code - I haven't checked - so it could take some time.

**Comment by jreiberkyle** [comment]
Oh, ok, cool! Yes, it would be great to update to the released version. 

This brings up something that's been bothering me, especially as I just went through the depreciation of python 2.7. As the repo is set up, it's a pain to make sure all notebooks run successfully when a library is updated. This is due to (1) manual involvement required to run each notebook and (2) some notebooks not being self-contained (assuming the user already downloaded a specific image). I have an issue open for auto-running the notebooks, #32. Requiring notebooks to be self-contained is a whole other issue and is a pre-req for #32 to be effective. What thoughts do you have on resolving this?
