### ISSUE TITLE
ndvi_planetscope notebook unexpected NDVI values

### ISSUE THREAD

**Issue by craigdsouza** [planetlabs/notebooks#66]
not sure this is the right place, but I have a query regarding one of the notebooks , 'ndvi_planetscope'
I ran the notebook for a scene I was interested in, 
Scene id: '20181002_045628_0f1a' 
item_type = 'PSScene4Band'
asset_type = 'analytic_sr'
everything runs ok, however the resulting NDVI I get is completely unexpected, largely in the range of 0.6-0.8 A Sentinel 2 image (TOA not SR) for the same date shows NDVI values, much smaller. Any idea what the issue might be? or if there is one

**Comment by jreiberkyle** [comment]
To compare apples to apples, I suggest comparing TOA to TOA. For that, you can look at the 'analytic' asset_type. Do the resulting NDVI's match up?

**Comment by craigdsouza** [comment]
so i looked at TOA(reflectance &  radiance) instead , the discrepancy is still there, but in this case NDVI is being underestimated vis-a-vis Sentinel.  I'm attaching histograms and thumbnail images for reference.
 
While I understand the histograms for the two images won't match exactly,  what I don't get is why NDVI over built up land and even river water is being overestimated to such a large degree upto values of 0.1-0.2 which is definitely unexpected. 
However note, the raw radiance image does show expected values over built up areas but here the histogram is skewed far left of the Sentinel histogram. Besides S2 is a reflectance image, not radiance so the two aren't comparable.

### 1. TOA Planet Scope Reflectance Image 2nd Oct 2018
![toa_reflectance-ndvi-histogram](https://user-images.githubusercontent.com/11412924/48519615-87bdce80-e893-11e8-8974-30affa7b1820.png)
![toa-reflectance-ndvi](https://user-images.githubusercontent.com/11412924/48519616-88566500-e893-11e8-8f42-304d254dc740.png)


### 2. TOA Planet Scope Radiance Image 2nd Oct 2018
![toa-radiance-ndvi-histogram](https://user-images.githubusercontent.com/11412924/48520029-30b8f900-e895-11e8-8078-eb0d936d5f03.png)
![toa-radiance-ndvi-fig](https://user-images.githubusercontent.com/11412924/48520035-39113400-e895-11e8-9722-685bba2876a0.png)


### 3. TOA Sentinel 2 Image 29 Sep 2018
![s2-ndvi-hist](https://user-images.githubusercontent.com/11412924/48518361-6ce95b00-e88f-11e8-96aa-7bb0eff47998.png)
![s2-ndvi-fig](https://user-images.githubusercontent.com/11412924/48518360-6c50c480-e88f-11e8-89b4-83e6e5f3b2f3.png)


### 3. SR Planet Scope Image 2nd Oct 2018
![sr-ndvi-histogram](https://user-images.githubusercontent.com/11412924/48518363-6ce95b00-e88f-11e8-9b3f-705b07ff036e.png)
![sr-ndvi-fig](https://user-images.githubusercontent.com/11412924/48518362-6ce95b00-e88f-11e8-9b21-edf54aa2f84e.png)

**Comment by craigdsouza** [comment]
Hey,
any thoughts here?

Best
Craig

**Comment by jreiberkyle** [comment]
Hey Craig,

Sorry for the delay over the holidays. So first of all, what comes into mind is the fact that NDVI indices are really best used for comparison within a sensor type. This is primarily because the spectral bands differ between sensors (e.g. the 'red' band is actually measuring different wavelengths). This is true for Landsat, Sentinel, and most sensors. Within a sensor 'family', such as Landsat, the design is such that those differences are minimized as much as possible. Planetscope sensors have a different spectral response than Sentinel, so I would expect NDVI to be different regardless of the target (water, vegetation, built-up areas). It is possible to minimize these differences by 'calibrating' the NDVI values using known targets, but that requires care to avoid introducing errors.

A good starting point is the description of the spectral response of the PlanetScope sensors, given [here](https://www.planet.com/products/planet-imagery/) (click the link to Download Full Specs).
